# Generated by Django 4.2.3 on 2023-07-25 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test_F', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='First_table',
            new_name='F_table',
        ),
    ]
